version: '3.8'

services:
  celery:
    build: .
    container_name: celery_master
    restart: always
    environment:
      - CELERY_BROKER_URL=pyamqp://user:password@192.168.196.159//
      - CELERY_RESULT_BACKEND=rpc://
    networks:
      - my_network

  flower:
    image: mher/flower
    container_name: flower
    restart: always
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=pyamqp://user:password@192.168.196.159//
    networks:
      - my_network

networks:
  my_network:
    external: true
